Implémentation tp5 checkstyle

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -20,7 +20,24 @@ jobs:
       - run: mvn -B test -Dmaven.test.failure.ignore=true
       - run: mvn jacoco:report
       - run : bash <(curl -s https://codecov.io/bash)
-
+      - run:
+          name: Mettre à jour le README
+          command: |
+            if [ $? -eq 0 ]; then
+              echo -e "![Static Badge](https://img.shields.io/badge/checkstyle-sucess-passing?color=green)" > README.md
+            else
+              echo -e "![Static Badge](https://img.shields.io/badge/checkstyle-fail-fail?color=red)" > README.md
+            fi
+      - run:
+          name: Commit et push du README
+          command: |
+            if [[ "$COMMIT_MESSAGE" != *"skip badge"* ]]; then
+              git config --global user.email "circleci@example.com"
+              git config --global user.name "CircleCI Bot"
+              git add README.md
+              git commit -m "Met à jour le statut du build dans le README, skip badge"
+              git push origin main
+            fi
 workflows:
   build_and_test:
     jobs:
